### ISSUE TITLE
feature request: line-conservative bang commands

### ISSUE THREAD

**Issue by amazingproducer** [vk3dan/sturdy-lidbot#1]
Delete the input lines for !commands and present their output as a webhook which mimics the requester where applicable. Also consider implementing the same, but with slash (`/command`) command input.

**Comment by vk3dan** [comment]
I will look at the first half at least on commands where this makes the most sense.

On the slash commands, discord.py doesn't yet support slash commands and the libraries that do support this are not mature and keep changing requiring rewrites to keep working and aren't fully compatible with discord.py's other functionality, so I will wait until discord.py supports this directly (they're saying about v2.0) rather than rewrite everything.

**Comment by amazingproducer** [comment]
Sounds good. I'll keep an eye out for this new feature!

**Comment by vk3dan** [comment]
I think I have updated the commands that make the most sense to be more line-conservative now 👍🥸
